Multi-platform compile script

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -1,6 +1,43 @@
 #!/bin/bash
 
-QMCOMP=$(brew --prefix qt5)/bin/qmake
+platform=`uname`
+if [[ "$platform" == "Linux" ]]; then
+    qtchooser >> /dev/null 2> /dev/null
+    QMAKERET=`echo $?`
+
+    if [ $QMAKERET -ne 127 ]; then
+      VERSION=0
+      for v in `qtchooser -l`; do
+        if [[ $v == 5* ]]; then
+        VERSION=`echo $v`
+        break
+        fi
+      done
+      if [ "$VERSION" == 0 ]; then
+        echo "!!!!!!!! it seems you don't have qt5 installed, aborting compilation !!!!!!!!"
+        exit 1
+      fi
+      QMCOMP="qtchooser -run-tool=qmake -qt=$VERSION"
+      echo "compiler command: \"$QMCOMP\""
+    else
+      echo "!!!!!!!! it seems you don't have qt5 installed, aborting compilation !!!!!!!!"
+      exit 1
+    fi
+elif [[ "$platform" == "Darwin" ]]; then
+    which -s brew
+    if [[ $? != 0 ]] ; then
+        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+    fi
+    for pkg in qt5 libelf boost; do
+        if brew list -1 | grep -q "^${pkg}\$"; then
+            echo "Package '$pkg' is installed"
+        else
+            echo "Package '$pkg' is not installed"
+            brew install "$pkg"
+        fi
+    done
+    QMCOMP=$(brew --prefix qt5)/bin/qmake
+fi
 
 ./configure
 
