readme and script fix

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -1,13 +1,25 @@
 #!/bin/bash
 
-qmake-qt5 >> /dev/null 2> /dev/null
+qtchooser >> /dev/null 2> /dev/null
 QMAKERET=`echo $?`
 
 if [ $QMAKERET -ne 127 ]; then
-  QMCOMP=qmake-qt5
+  VERSION=0
+  for v in `qtchooser -l`; do
+    if [[ $v == 5* ]]; then
+	VERSION=`echo $v`
+	break
+    fi
+  done
+  if [ "$VERSION" == 0 ]; then
+    echo "!!!!!!!! it seems you don't have qt5 installed, aborting compilation !!!!!!!!"
+    exit 1
+  fi
+  QCOMP="qtchooser -run-tool=qmake -qt=$VERSION"
+  echo "compiler command: \"$QCOMP\""
 else
-  QMCOMP=qmake
-  echo "!!!!!!!! it seems you don't have qt5 installed, this may lead to wrong compilation !!!!!!!!"
+  echo "!!!!!!!! it seems you don't have qt5 installed, aborting compilation !!!!!!!!"
+  exit 1
 fi
 
 ./configure
